service: music

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: handler.getTrack
    events:
      - http:
          path: tracks
          method: post

custom:
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-python-requirements
  - serverless-wsgi
