service: music

provider:
  name: aws
  runtime: python3.7

functions:
  getTrack:
    handler: wsgi.handler
    events:
      - http: 'POST /tracks'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-python-requirements
  - serverless-wsgi
